site:
  title: Boost.TypeLayout Documentation
  url: https://github.com/ximicpp/TypeLayout
  start_page: typelayout::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: doc

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

runtime:
  fetch: true

asciidoc:
  attributes:
    # Enable syntax highlighting
    source-highlighter: highlight.js
    # C++ as default language for code blocks
    source-language: cpp
    # Enable experimental features
    experimental: true
    # Icons
    icons: font
    # C++ version shortcuts
    cpp: 'C++'
    cpp11: 'C++11'
    cpp14: 'C++14'
    cpp17: 'C++17'
    cpp20: 'C++20'
    cpp23: 'C++23'
    cpp26: 'C++26'
    # Project info
    project-version: '1.0.0'
    boost-version: '1.87.0'

output:
  dir: doc/build/site